nacos:
  config:
    server-addr: 111.229.95.167:8848
    group: DEFAULT_GROUP
    username: nacos
    password: nacos

dubbo:
  application:
    name: market-use
  registry:
    address: nacos://${nacos.config.server-addr}
    timeout: 5000
    username: nacos
    password: nacos
  protocol:
    name: dubbo
# 应用配置
app:
  config:
    # 版本，方便通过接口版本升级
    api-version: v1
    # 跨域，开发阶段可以设置为 * 不限制
    cross-origin: '*'